# Generated by Django 2.1.7 on 2019-07-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contant',
            new_name='content',
        ),
    ]
